name: Deploy Crate

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-release
        run: |
          cargo install cargo-release
      - name: Release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Prep auth for pushing tags
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config http.sslVerify false
          git config --local user.email kylewrader@gmail.com
          git config --local user.name ${GITHUB_ACTOR}
          git remote set-url origin $remote_repo

          # Run Cargo Release
          cargo release --config release.toml --execute --no-confirm
